### ISSUE TITLE
Not working when using view binding

### ISSUE THREAD

**Issue by TieuNhi95** [vivid-money/prefetchviewpool#2]
By default, i count number of viewHolder which is created, as soon as open app it prefetch about 20 item, when i submitList it doesn't create any items.
However when i use viewBinding, after submitList the number of items creates about 17-20 items further.

**Comment by sergei-lapin** [comment]
Could you please provide MRE? From description you provided it's hard for me to understand what issue this might be.

**Comment by TieuNhi95** [comment]
I can't push code to your git.
`remote: Permission to vivid-money/prefetchviewpool.git denied to TieuNhi95.
fatal: unable to access 'https://github.com/vivid-money/prefetchviewpool.git/': The requested URL returned error: 403`

**Comment by sergei-lapin** [comment]
MRE (Minimal Reproducible Example) should be provided either via gist or repository in your profile

**Comment by TieuNhi95** [comment]
@sergei-lapin i just push to my github.
https://github.com/TieuNhi95/prefetchRecyclerView

**Comment by sergei-lapin** [comment]
Oh, you mean **DataBinding**. Lib works with **ViewBinding**, but, apparently, not with **DataBinding**. In our main project we don't use **DataBinding** so we were not aware about that. Try removing `<layout>` tag and use `buildFeatures.viewBinding = true` instead of `buildFeature.dataBinding = true`. In case you'll manage to get it working with **DataBinding** — PR is always welcome.

**Comment by sergei-lapin** [comment]
Closing as investigating **DataBinding** support isn't planned
